// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources/protos/user.proto

package com.example.demo.global.protos.user;

public interface UserCreateResOrBuilder extends
    // @@protoc_insertion_point(interface_extends:demo.UserCreateRes)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();
}
