// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources/protos/user.proto

package com.example.demo.global.protos.user;

public interface UserCreateReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:demo.UserCreateReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string email = 2;</code>
   * @return The email.
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 2;</code>
   * @return The bytes for email.
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>string password = 3;</code>
   * @return The password.
   */
  java.lang.String getPassword();
  /**
   * <code>string password = 3;</code>
   * @return The bytes for password.
   */
  com.google.protobuf.ByteString
      getPasswordBytes();

  /**
   * <code>.demo.GenderType gender = 4;</code>
   * @return The enum numeric value on the wire for gender.
   */
  int getGenderValue();
  /**
   * <code>.demo.GenderType gender = 4;</code>
   * @return The gender.
   */
  com.example.demo.global.protos.user.GenderType getGender();
}
