// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources/protos/user.proto

package com.example.demo.global.protos.user;

public final class UserProtos {
  private UserProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_demo_UserCreateReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_demo_UserCreateReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_demo_UserCreateRes_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_demo_UserCreateRes_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033resources/protos/user.proto\022\004demo\"`\n\rU" +
      "serCreateReq\022\014\n\004name\030\001 \001(\t\022\r\n\005email\030\002 \001(" +
      "\t\022\020\n\010password\030\003 \001(\t\022 \n\006gender\030\004 \001(\0162\020.de" +
      "mo.GenderType\"\033\n\rUserCreateRes\022\n\n\002id\030\001 \001" +
      "(\003*\"\n\nGenderType\022\010\n\004MALE\020\000\022\n\n\006FEMALE\020\001B3" +
      "\n#com.example.demo.global.protos.userB\nU" +
      "serProtosP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_demo_UserCreateReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_demo_UserCreateReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_demo_UserCreateReq_descriptor,
        new java.lang.String[] { "Name", "Email", "Password", "Gender", });
    internal_static_demo_UserCreateRes_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_demo_UserCreateRes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_demo_UserCreateRes_descriptor,
        new java.lang.String[] { "Id", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
